name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      tags:
        description: 'Test tags to run(eg. @smoke @regression)'
        required: false
        default: '@smoke'
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy: 
      matrix: 
        shardIndex: [1, 2] 
        shardTotal: [2] 
      max-parallel: 2
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      API_BASE_URL: ${{ secrets.API_BASE_URL }}
      WC_BASE_URL: ${{ secrets.WC_BASE_URL }}
      WC_CONSUMER_KEY: ${{ secrets.WC_CONSUMER_KEY }}
      WC_CONSUMER_SECRET: ${{ secrets.WC_CONSUMER_SECRET }}
      TEST_USER_1_EMAIL: ${{ secrets.TEST_USER_1_EMAIL }}
      TEST_USER_1_PASSWORD: ${{ secrets.TEST_USER_1_PASSWORD }}
      TEST_USER_2_EMAIL: ${{ secrets.TEST_USER_2_EMAIL }}
      TEST_USER_2_PASSWORD: ${{ secrets.TEST_USER_2_PASSWORD }}
      TEST_USER_3_EMAIL: ${{ secrets.TEST_USER_3_EMAIL }}
      TEST_USER_3_PASSWORD: ${{ secrets.TEST_USER_3_PASSWORD }}
      TEST_USER_4_EMAIL: ${{ secrets.TEST_USER_4_EMAIL }}
      TEST_USER_4_PASSWORD: ${{ secrets.TEST_USER_4_PASSWORD }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17' 
    - name: Run Playwright tests
      run: npx playwright test --project=chromium --project=firefox --project=webkit --workers=4 --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}  
    - name: Upload blob report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: blob-report-${{matrix.shardIndex}}
        path: blob-report
        retention-days: 30
    - name: Upload allure-result
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: allure-results-${{matrix.shardIndex}}
        path: allure-results
        retention-days: 30
    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results-${{matrix.shardIndex}}
        path: test-results/
        retention-days: 30
  merge-reports:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps: 
      - uses: actions/checkout@v4
      - name: merge blob reports
        uses: actions/download-artifact@v4
        with:
          pattern: blob-report-*
          merge-multiple: true
          path: all-blob-reports
      - run: npx playwright merge-reports --reporter=html ./all-blob-reports
      - name: combine allure-results
        uses: actions/download-artifact@v4
        with:
          pattern: allure-results-*
          merge-multiple: true
          path: allure-results

